### ISSUE TITLE
Dockerfile pour RoR

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#10]
Besoins:

* build-essential
* nodejs
* capybara-webkit (libqt4-webkit, libqt4-dev et xvfb)
* **postgres** (libpq-dev)
* **redis**
* **mariadb-client**
* ssmtp
* sqlite3
* nokogiri (libxml2-dev et libxslt1-dev)
* ruby 2.2
* therubyracer (libv8-dev)
* bundler

via [_rails on docker_](https://robots.thoughtbot.com/rails-on-docker) et [docker-library/ruby](https://github.com/docker-library/ruby)

**Comment by greut** [comment]
Not bad.

![ror](https://cloud.githubusercontent.com/assets/1388/11009265/ff4ad68e-84d5-11e5-9640-309318bdaca4.png)

**Comment by greut** [comment]
Pas aussi joli que passenger mais tellement plus simple de tout faire avec un petit fichier ini.

![rack](https://cloud.githubusercontent.com/assets/1388/11027592/36297010-86b7-11e5-98b4-bac417ddb0e2.png)

**Comment by osaris** [comment]
@greut le restart.txt classique n'est pas spécifique à la version payante, c'est la feature de "rolling restart" qui l'est il me semble.

**Comment by greut** [comment]
@osaris m'kay, je vois.

Je m'en suis sorti plus simplement avec `uwsgi` qu'avec `passenger` qui part un peu un vrille à cause de `rvm`. Il y a un peu moins de _magie_ et c'est plus proche du déploiement avec php-fpm qui est utilisé pour Laravel; le redémarrage manuel avec un `touch config.ru` mis à part.

```nginx
server {
    listen 80;
    server herpderp.srvz-webapp.he-arc.ch;

    root /var/www/app/public;

    location / {
        try_files $uri @uwsgi;
    }

    location @uwsgi {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:3031;
        uwsgi_modifier1 7;
    }
}
```

```ini
[uwsgi]
socket = 127.0.0.1:3031
rack = /var/www/app/config.ru

processes = 4
lazy-apps = true
thunder-lock = true

; change me
chdir = /var/www/app
rbrequire = bundler/setup
env = RAILS_ENV=development BUNDLE_GEMFILE=Gemfile

; run `touch config.ru` to restart the webserver
touch-reload = /var/www/app/config.ru
```

**Comment by osaris** [comment]
Ouais alors rvm + passenger c'est pas toujours la joie.

Pas de problème pour uwsgi, je ferai quelques tests dès que tu as une VM à me mettre à dispo et puis je m'appuierai sur toi si nécessaire :)

**Comment by greut** [comment]
@osaris ça ne saurait tarder.

**Comment by greut** [comment]
problème l'installation de Vundle.

**Comment by osaris** [comment]
FYI j'ai profité de passer sous linux pour utiliser uwsgi pour le dév en
local, j'ai un peu lutté pour m'en sortir mais ça tourne et comme ça je
suis pas trop dépaysé pour le workshop déploiement ;-)

2015-11-25 21:02 GMT+01:00 Yoan Blanc <notifications@github.com>:

**Comment by greut** [comment]
@osaris cool. Bienvenue sous nunux!
