### ISSUE TITLE
CVGenerator Migration

### ISSUE THREAD

**Issue by Drakesinger** [HE-Arc/webapp-server#12]
Malheureusement les migrations ne marchent pas:
![capture](https://cloud.githubusercontent.com/assets/5525720/11819525/ab260854-a360-11e5-992c-bf4b58f14927.JPG)

Essayé:
http://stackoverflow.com/questions/2412009/starting-with-zend-tutorial-zend-db-adapter-throws-exception-sqlstatehy000
http://stackoverflow.com/questions/19475762/setting-up-laravel-on-a-mac-php-artisan-migrate-error-no-such-file-or-directory

Changé le fichier php.ini avec la route vers le php5-fpm.sock (ou quelque chose du genre).
Même erreur.

**Comment by greut** [comment]
https://github.com/HE-Arc/demo-laravel-application/commit/14c44b6d7d484b86ac07978f248c29ce892c7cb1#diff-8a025ad5d4f4fade612727b1bb0e974f

**Comment by Drakesinger** [comment]
Le README du serveur ne correspond pas avec le readme passé.
Et l'erreur n'est pas spécifique (je trouve).

Par contre c'est reglé.

**Comment by greut** [comment]
L'erreur dit qu'il essaie de se connecter sur le serveur local et le serveur MySQL n'est pas sur la même machine.

le README a un peu changé pour le mieux, mais les deux sont sensés fonctionner.
