### ISSUE TITLE
Changement de username

### ISSUE THREAD

**Issue by Rocla** [HE-Arc/webapp-server#17]
Bonjour,

Je souhaitais savoir la procédure pour changer mon username. En effet, roman est déprécié, romain est d'actualité.

Bien cordialement,
Romain Claret

**Comment by greut** [comment]
Avez-vous essayé?

`$ man` [`usermod`](http://manpages.ubuntu.com/manpages/trusty/man8/usermod.8.html)

**Comment by Rocla** [comment]
Alors, pour changer le username ça marche nickel:
`usermod -l roman romain`

Cependant, pour changer le home... ça ne marche pas au niveau du ~
J'ai fait:
`sudo su`
`usermod -m -d /home/romain romain`

**Comment by Rocla** [comment]
Bon ben.. J'ai cassé mon username... Je ne peux plus me connecter en SSH 👌

**Comment by greut** [comment]
Ben bravo ;-)

**Comment by greut** [comment]
ça devrait le faire à présent.

```
finance:x:999:999:GROUP:/var/www:
yoan:x:1000:999:Teacher:/home/yoan:/bin/bash
david:x:1001:999:Teacher:/home/david:/bin/bash
fabio:x:1002:999:INF3dlm-a:/home/fabio:/bin/bash
matthieu:x:1003:999:INF3dlm-b:/home/matthieu:/bin/bash
romain:x:1004:999:INF3dlm-b:/home/romain:/bin/bash
```

**Comment by Rocla** [comment]
Top :+1: merci beaucoup !
