### ISSUE TITLE
FinanceCloud

### ISSUE THREAD

**Issue by matbandeli** [HE-Arc/webapp-server#18]
Bonjour,

Je n'ai pas de compte utilisateur sur le projet FinanceCloud.
Pouvez-vous me créer un compte?

Mon pseudo : matthieu

Voici également ma nouvelle clé publique : 

---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20160215"
AAAAB3NzaC1yc2EAAAABJQAAAQEAhB3yH4N6Q9aazqsc/w7Q9uy3FXNlD7dsSKvC
6hLk43rXeG6ej/YoK2EujjknxV6reCuxr+gavlPhh6SpdKKmLnE8iEbs/Rw6xHFh
o+qcDx0sepBpDfxc8VXfR4owzJw8xrbRxilSXoEOotJzunOqrYgLWK4tUJ2cLIgW
wtHEXysKb3ZceDdJkBg639LGlWnynWhYEgcKCgcVGyMWcpBTz3c9WKVldlrQUpmP
CDZ8bYyzARWwmxZVOr/wKXYYR/xSwvgyMG1t92inpQegaYFdD4/+TWoy3kqo2Yqx
wk0ILgKvCy7uO9kLxYr2rP9T+yal7/f7sYqI70+VpLNFGUK2Pw==
---- END SSH2 PUBLIC KEY ----

**Comment by greut** [comment]
En effet, je vous avais interverti de groupe avec votre collègue @Drakesinger 

Vous à présent cette clé ainsi que celle installée dans [github](https://api.github.com/users/matbandeli/keys).
