### ISSUE TITLE
Tester cvgenerator

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#2]
Hey hey,

[cvgenerator](http://cvgenerator.srvz-webapp.he-arc.ch) est prêt. Ca se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `horia`, `fabio` ou `joel`:
    * avec un système POSIX: `$ ssh -p 2201 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2201` ]
3. ???
4. Profit! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou suivre le fichier [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md).

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. :shipit:

A testé et a approuvé:
* [x] @Drakesinger
* [x] @fabioman
* [x] @Arnianor

**Comment by Drakesinger** [comment]
Tested.

**Comment by Arnianor** [comment]
Tested

**Comment by fabioman** [comment]
Tested
