### ISSUE TITLE
Tester avedis

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#3]
Glop,

[Avedis](http://avedis.srvz-webapp.he-arc.ch) est prêt. Pour vous en servir, ça se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `lucas`, `gabriel` ou `margaux`:
    * avec un système POSIX: `$ ssh -p 2203 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2203` ]
3. ???
4. Profit! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou lire le [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md) et tester Laravel sur cette plateforme.

A testé et a approuvé:
* [x] @LucasBeltrame
* [x] @CrumbleZ
* [x] @margauxdivernois

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. Ou si ça ne le fait pas, comment on peut vous aider.

**Comment by CrumbleZ** [comment]
Bonjour... Je n'ai apparemment pas compris comment on utilisait les clés SSH et je n'ai donc pas de paire public/privé sur la première clé que je vous ai transmis

J'ai regénéré une paire de clés (conscieusement conservées cette fois)... La nouvelle clé publique à été ajouté sur le github et est nommée "CrumbleZ@Avedis PuK"

Merci de me dire lorsque cela est mis à jour pour que je puisse tenter la connexion. Merci beaucoup.

**Comment by greut** [comment]
@CrumbleZ voilà, j'ai mis à jour vos clés. Il y a les deux de [votre compte](https://api.github.com/users/CrumbleZ/keys) (13799206 et 13894708).

**Comment by CrumbleZ** [comment]
C'est nickel, c'est fonctionnel.. Merci bien

**Comment by greut** [comment]
:+1:

**Comment by margauxdivernois** [comment]
Ca fonctionne tout bien, merci beaucoup :)

**Comment by greut** [comment]
Tip top.
