### ISSUE TITLE
Tester look4cards

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#4]
Glop,

[Look4Cards](http://look4cards.srvz-webapp.he-arc.ch) est prêt. Pour vous en servir, ça se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `lukas`, `quentin` ou `thomas`:
    * avec un système POSIX: `$ ssh -p 2204 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2204` ]
3. ???
4. Profit! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou lire le [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md) et tester Laravel sur cette plateforme.

A testé et a approuvé:
* [x] @LukasBitter
* [x] @thomasroulin
* [x] @roflolilolmao

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. Ou si ça ne le fait pas, comment on peut vous aider.

**Comment by thomasroulin** [comment]
Hello,

Le serveur a effectivement bien l'air en ligne, par contre nous ne connaissons pas nos mots de passe. Nous n'avons donc pas encore pu nous connecter.

**Comment by greut** [comment]
@thomasroulin il n'y a pas de mot de passe. C'est [votre clé SSH](https://api.github.com/users/thomasroulin/keys) qui devrait vous authentifier.

**Comment by thomasroulin** [comment]
@greut Effectivement, c'est la première fois que nous utilisons ce système. Moi-même et @roflolilolmao avons pu nous connecter sans problème et sommes en train de configurer le serveur.

Merci !

**Comment by greut** [comment]
C'est beau :wink:!

Petit conseil: prenez des notes des choses que ce vous changer sur la machine. On ne sait jamais. Il est possible que vous soyez amenés à devoir le refaire.

**Comment by LukasBitter** [comment]
@greut Salut, c'est bon, ça marche pour moi aussi.

**Comment by greut** [comment]
Gracias!
