### ISSUE TITLE
Tester tournoi

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#5]
Hej hej,

[Tournoi](http://tournoi.srvz-webapp.he-arc.ch) est prêt. Pour vous en servir, ça se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `bastien`, `leonardo` ou `jeshon`:
    * avec un système POSIX: `$ ssh -p 2205 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2205` ]
3. ???
4. Profit! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou lire le [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md) et tester Laravel sur cette plateforme.

A testé et a approuvé:
* [x] @ouatedephoque
* [x] @leonardodistasio
* [ ] @bastou2316

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. Ou si ça ne le fait pas, comment on peut vous aider.

**Comment by leonardodistasio** [comment]
J'ai juste une question : on doit utiliser quel mot de passe pour pouvoir se connecter ? Merci d'avance

**Comment by greut** [comment]
Aucun, [votre clé SSH](https://api.github.com/users/leonardodistasio/keys) est là pour ça.

**Comment by leonardodistasio** [comment]
C'est tout bon pour la connexion, merci !

**Comment by greut** [comment]
:+1:

**Comment by ouatedephoque** [comment]
C'est tout bon pour la connexion, merci !
