### ISSUE TITLE
fix huge nginx logs in _data volumes "cannot bind() to 0.0.0.0" 

### ISSUE THREAD

**Issue by grunenwald** [HE-Arc/webapp-server#61]
Workaround

On the containers : 
`sudo truncate -s0 /var/log/nginx/error.log`

On the host : 
`for f in find "/var/lib/docker/containers/" -iname "*.log"; do echo truncate $f; end`

**Comment by greut** [comment]
This is probably not up to date.

https://github.com/HE-Arc/webapp-server/blob/master/files/base/vhost.logrotate
