### ISSUE TITLE
SSH port inaccessible from outside HE-Arc network

### ISSUE THREAD

**Issue by Zegorax** [HE-Arc/webapp-server#71]
With the current implementation of webapp-server, it is currently impossible to access the different SSH ports on the containers. 

Is it possible to make them accessible, to allow automated system to perform automatic deployment tasks ?

**Comment by Zegorax** [comment]
More details in the `auto-deploy` job in this PR's checks. https://github.com/HE-Arc/museodio/pull/22

**Comment by greut** [comment]
IIRC the VPN is always required.

**Comment by stevevisinand** [comment]
We have a Gitlab and Gitlab runners in DMZ, you normally will be able to access to the SRVZ's SSH from here.

If moving the repository to gitlab is not an issue, it can be a good workaround.

**Comment by Zegorax** [comment]
@stevevisinand Yes that is what I was doing for last year's projects. However, this one is required to be on GitHub, and that is why I opened this issue

**Comment by stevevisinand** [comment]
Hum, or we have an old Jenkins in DMZ too, not used and not updated anymore but it can do the job.

**Comment by Zegorax** [comment]
It's not a problem, I will make a script triggered by an HTTP request that will do the job instead

**Comment by stevevisinand** [comment]
Otherwise, it seems that it's possible to use Gitlab CI with external repositories but we haven't the right license for ...

https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/
