### ISSUE TITLE
Tester guesthouse

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#8]
Plop!

[GuestHouse](http://guesthouse.srvz-webapp.he-arc.ch) est prêt. Pour vous en servir, ça se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `wassim`, `tom` ou `jeremy`:
    * avec un système POSIX: `$ ssh -p 2207 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2207` ]
3. :question: :grey_question: :question:
4. Profit :moneybag:! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou lire le [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md) et tester Laravel sur cette plateforme.

A testé et a approuvé:
* [ ] @TomRey
* [ ] @wassimajjali
* [x] @TheWirjy

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. Ou si ça ne le fait pas, comment on peut vous aider. :shipit:

**Comment by TheWirjy** [comment]
c'est tout bon
