### ISSUE TITLE
Tester tsuro

### ISSUE THREAD

**Issue by greut** [HE-Arc/webapp-server#9]
Plop!

[Tsuro](http://tsuro.srvz-webapp.he-arc.ch) est prêt. Pour vous en servir, ça se passe en 4 étapes faciles:

1. Vous mettre sur le VPN de l'école (et oui)
2.  Vous connecter en tant que `matthieu`, `martin` ou `nicolas`:
    * avec un système POSIX: `$ ssh -p 2208 <prénom>@srvz-webapp.he-arc.ch`
    * avec putty: [ Hostname: `srvz-webapp.he-arc.ch`] [ Port: `2208` ]
3. :question: :grey_question: :question:
4. Profit :moneybag:! 

Ensuite, vous pouvez corriger le fichier qui s'affiche actuellement (`www/index.php`) ou lire le [`README.md`](/HE-Arc/webapp-server/blob/master/files/templates/README.md) et tester Laravel sur cette plateforme.

A testé et a approuvé:
* [x] @martinkunzi
* [x] @matbandeli
* [x] @thegazou

Merci de mettre un petit commentaire ci-dessous quand vous avez réussi à vos y logguer, et que ça le fait. Si ça ne le fait pas, dites-nous comment on peut vous aider. :shipit:

**Comment by thegazou** [comment]
Testé et approuvé!

**Comment by greut** [comment]
@martinkunzi et @matbandeli j'ai mis à jour vos clés.

**Comment by matbandeli** [comment]
merci

2015-10-08 9:30 GMT+02:00 Yoan Blanc <notifications@github.com>:

**Comment by martinkunzi** [comment]
merci beaucoup
________________________________
De : Yoan Blanc [notifications@github.com]
Envoy� : jeudi 8 octobre 2015 09:30
� : HE-Arc/webapp-server
Cc : K�nzi Martin
Objet : Re: [webapp-server] Tester tsuro (#9)


@martinkunzi<https://github.com/martinkunzi> et @matbandeli<https://github.com/matbandeli> j'ai mis � jour vos cl�s.

�
